### PR TITLE
Rebase: ibm-vpc-block-csi-driver v4.4.4

### PR DESCRIPTION
**Pull request by dobsonj**
This PR rebases on [ibm-vpc-block-csi-driver v4.4.4](https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/releases/tag/v4.4.4)

Fixing the following bugs:
- https://bugzilla.redhat.com/show_bug.cgi?id=2067842
- https://bugzilla.redhat.com/show_bug.cgi?id=2078727
- https://bugzilla.redhat.com/show_bug.cgi?id=2073617
- https://bugzilla.redhat.com/show_bug.cgi?id=2047732

Upstream comparison:
https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/compare/v4.4.4...dobsonj:rebase-v4.3.0

/cc @openshift/storage @chao007

### CODE REVIEW

**Comment by dobsonj** [comment]
/hold until https://github.com/openshift/ibm-vpc-block-csi-driver-operator/pull/37 merges
`KUBE_NODE_NAME` is now expected to be defined in the controller yaml:
https://github.com/openshift/ibm-vpc-block-csi-driver/pull/14/files#diff-ddef8045da8242ba329365e0ab1bae6e64a6789ab640199a3ce134ae554e1c9fR111-R115

**Comment by dobsonj** [comment]
/hold
I built and deployed a release image with these 3 PR's:
https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/189
https://github.com/openshift/ibm-vpc-block-csi-driver-operator/pull/37
https://github.com/openshift/ibm-vpc-block-csi-driver/pull/14

But csi-driver-registrar was stuck in a crash loop:
```
$ oc get pods -n openshift-cluster-csi-drivers
NAME                                                READY   STATUS             RESTARTS         AGE
ibm-vpc-block-csi-controller-5fd997989-k78cx        5/5     Running            3 (3h29m ago)    3h42m
ibm-vpc-block-csi-driver-operator-c9597f894-6xs9b   1/1     Running            0                3h43m
ibm-vpc-block-csi-node-7gplx                        2/3     CrashLoopBackOff   47 (56s ago)     3h42m
ibm-vpc-block-csi-node-fwlt7                        2/3     CrashLoopBackOff   45 (3m11s ago)   3h34m
ibm-vpc-block-csi-node-pnnlj                        2/3     CrashLoopBackOff   45 (2m40s ago)   3h34m
ibm-vpc-block-csi-node-rh7hc                        2/3     CrashLoopBackOff   45 (2m22s ago)   3h34m
ibm-vpc-block-csi-node-vgvkw                        2/3     CrashLoopBackOff   47 (3m ago)      3h42m
ibm-vpc-block-csi-node-wjgzq                        2/3     CrashLoopBackOff   47 (50s ago)     3h42m

$ oc get pods -n openshift-cluster-csi-drivers ibm-vpc-block-csi-node-7gplx -o yaml
...
  containerStatuses:
  - containerID: cri-o://bfb707b97638b4ed1338726a3953b7a869051395fcf081d2c5eecc3f64bdf731
    image: registry.build01.ci.openshift.org/ci-ln-kcn2d0b/stable@sha256:cc17e05da5cfbabe7de83359189e4fe5cc97690e3304046705afdbbc30b34433
    imageID: registry.build01.ci.openshift.org/ci-ln-kcn2d0b/stable@sha256:cc17e05da5cfbabe7de83359189e4fe5cc97690e3304046705afdbbc30b34433
    lastState:
      terminated:
        containerID: cri-o://bfb707b97638b4ed1338726a3953b7a869051395fcf081d2c5eecc3f64bdf731
        exitCode: 1
        finishedAt: "2022-05-10T23:11:23Z"
        reason: Error
        startedAt: "2022-05-10T23:11:21Z"
    name: csi-driver-registrar
    ready: false
    restartCount: 48
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=csi-driver-registrar pod=ibm-vpc-block-csi-node-7gplx_openshift-cluster-csi-drivers(4b9dc4dd-6475-4bba-b8bd-bb456767a565)
        reason: CrashLoopBackOff
```

Because "driverNodeID must not be empty"
```
$ oc logs -n openshift-cluster-csi-drivers ibm-vpc-block-csi-node-7gplx -c csi-driver-registrar
I0510 23:11:21.867201       1 main.go:164] Version: v1.0.0-rc1-487-g629e85bf-dirty
I0510 23:11:21.867576       1 main.go:165] Running node-driver-registrar in mode=registration
I0510 23:11:21.868425       1 main.go:189] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0510 23:11:21.869137       1 main.go:196] Calling CSI driver to discover driver name
I0510 23:11:21.872376       1 main.go:206] CSI driver name: "vpc.block.csi.ibm.io"
I0510 23:11:21.873473       1 node_register.go:52] Starting Registration Server at: /registration/vpc.block.csi.ibm.io-reg.sock
I0510 23:11:21.873808       1 node_register.go:61] Registration Server started at: /registration/vpc.block.csi.ibm.io-reg.sock
I0510 23:11:21.874298       1 node_register.go:91] Skipping healthz server because HTTP endpoint is set to: ""
I0510 23:11:23.781595       1 main.go:100] Received GetInfo call: &InfoRequest{}
I0510 23:11:23.781978       1 main.go:107] "Kubelet registration probe created" path="/var/lib/kubelet/plugins/vpc.block.csi.ibm.io/registration"
I0510 23:11:23.817168       1 main.go:118] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:false,Error:RegisterPlugin error -- plugin registration failed with err: error adding CSI driver node info: driverNodeID must not be empty,}
E0510 23:11:23.817215       1 main.go:120] Registration process failed with error: RegisterPlugin error -- plugin registration failed with err: error adding CSI driver node info: driverNodeID must not be empty, restarting registration container.
```

That error comes from:
https://github.com/openshift/kubernetes/blob/69213f85dee380a180f1c4f141f482a8c7cbcac3/pkg/volume/csi/nodeinfomanager/nodeinfomanager.go#L111

Something in this PR must have changed that behavior. For reference, these are the labels that are set on the node:
```
$ oc get nodes jdobson-cluster01-c5wc9-master-2 -o yaml
...
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: bx2-4x16
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: us-south
    failure-domain.beta.kubernetes.io/zone: us-south-3
    ibm-cloud.kubernetes.io/worker-id: 0737_69aa2790-f4e4-4f8f-9260-661c1c164f48
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: jdobson-cluster01-c5wc9-master-2
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
    node.kubernetes.io/instance-type: bx2-4x16
    node.openshift.io/os_id: rhcos
    topology.kubernetes.io/region: us-south
    topology.kubernetes.io/zone: us-south-3
    vpc-block-csi-driver-labels: "true"
```

@ambiknai do you have any ideas?

**Comment by ambiknai** [comment]
> /hold I built and deployed a release image with these 3 PR's: [openshift/cluster-cloud-controller-manager-operator#189](https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/189) [openshift/ibm-vpc-block-csi-driver-operator#37](https://github.com/openshift/ibm-vpc-block-csi-driver-operator/pull/37) #14
> 
> But csi-driver-registrar was stuck in a crash loop:
> 
> ```
> $ oc get pods -n openshift-cluster-csi-drivers
> NAME                                                READY   STATUS             RESTARTS         AGE
> ibm-vpc-block-csi-controller-5fd997989-k78cx        5/5     Running            3 (3h29m ago)    3h42m
> ibm-vpc-block-csi-driver-operator-c9597f894-6xs9b   1/1     Running            0                3h43m
> ibm-vpc-block-csi-node-7gplx                        2/3     CrashLoopBackOff   47 (56s ago)     3h42m
> ibm-vpc-block-csi-node-fwlt7                        2/3     CrashLoopBackOff   45 (3m11s ago)   3h34m
> ibm-vpc-block-csi-node-pnnlj                        2/3     CrashLoopBackOff   45 (2m40s ago)   3h34m
> ibm-vpc-block-csi-node-rh7hc                        2/3     CrashLoopBackOff   45 (2m22s ago)   3h34m
> ibm-vpc-block-csi-node-vgvkw                        2/3     CrashLoopBackOff   47 (3m ago)      3h42m
> ibm-vpc-block-csi-node-wjgzq                        2/3     CrashLoopBackOff   47 (50s ago)     3h42m
> 
> $ oc get pods -n openshift-cluster-csi-drivers ibm-vpc-block-csi-node-7gplx -o yaml
> ...
>   containerStatuses:
>   - containerID: cri-o://bfb707b97638b4ed1338726a3953b7a869051395fcf081d2c5eecc3f64bdf731
>     image: registry.build01.ci.openshift.org/ci-ln-kcn2d0b/stable@sha256:cc17e05da5cfbabe7de83359189e4fe5cc97690e3304046705afdbbc30b34433
>     imageID: registry.build01.ci.openshift.org/ci-ln-kcn2d0b/stable@sha256:cc17e05da5cfbabe7de83359189e4fe5cc97690e3304046705afdbbc30b34433
>     lastState:
>       terminated:
>         containerID: cri-o://bfb707b97638b4ed1338726a3953b7a869051395fcf081d2c5eecc3f64bdf731
>         exitCode: 1
>         finishedAt: "2022-05-10T23:11:23Z"
>         reason: Error
>         startedAt: "2022-05-10T23:11:21Z"
>     name: csi-driver-registrar
>     ready: false
>     restartCount: 48
>     started: false
>     state:
>       waiting:
>         message: back-off 5m0s restarting failed container=csi-driver-registrar pod=ibm-vpc-block-csi-node-7gplx_openshift-cluster-csi-drivers(4b9dc4dd-6475-4bba-b8bd-bb456767a565)
>         reason: CrashLoopBackOff
> ```
> 
> Because "driverNodeID must not be empty"
> 
> ```
> $ oc logs -n openshift-cluster-csi-drivers ibm-vpc-block-csi-node-7gplx -c csi-driver-registrar
> I0510 23:11:21.867201       1 main.go:164] Version: v1.0.0-rc1-487-g629e85bf-dirty
> I0510 23:11:21.867576       1 main.go:165] Running node-driver-registrar in mode=registration
> I0510 23:11:21.868425       1 main.go:189] Attempting to open a gRPC connection with: "/csi/csi.sock"
> I0510 23:11:21.869137       1 main.go:196] Calling CSI driver to discover driver name
> I0510 23:11:21.872376       1 main.go:206] CSI driver name: "vpc.block.csi.ibm.io"
> I0510 23:11:21.873473       1 node_register.go:52] Starting Registration Server at: /registration/vpc.block.csi.ibm.io-reg.sock
> I0510 23:11:21.873808       1 node_register.go:61] Registration Server started at: /registration/vpc.block.csi.ibm.io-reg.sock
> I0510 23:11:21.874298       1 node_register.go:91] Skipping healthz server because HTTP endpoint is set to: ""
> I0510 23:11:23.781595       1 main.go:100] Received GetInfo call: &InfoRequest{}
> I0510 23:11:23.781978       1 main.go:107] "Kubelet registration probe created" path="/var/lib/kubelet/plugins/vpc.block.csi.ibm.io/registration"
> I0510 23:11:23.817168       1 main.go:118] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:false,Error:RegisterPlugin error -- plugin registration failed with err: error adding CSI driver node info: driverNodeID must not be empty,}
> E0510 23:11:23.817215       1 main.go:120] Registration process failed with error: RegisterPlugin error -- plugin registration failed with err: error adding CSI driver node info: driverNodeID must not be empty, restarting registration container.
> ```
> 
> That error comes from: https://github.com/openshift/kubernetes/blob/69213f85dee380a180f1c4f141f482a8c7cbcac3/pkg/volume/csi/nodeinfomanager/nodeinfomanager.go#L111
> 
> Something in this PR must have changed that behavior. For reference, these are the labels that are set on the node:
> 
> ```
> $ oc get nodes jdobson-cluster01-c5wc9-master-2 -o yaml
> ...
>   labels:
>     beta.kubernetes.io/arch: amd64
>     beta.kubernetes.io/instance-type: bx2-4x16
>     beta.kubernetes.io/os: linux
>     failure-domain.beta.kubernetes.io/region: us-south
>     failure-domain.beta.kubernetes.io/zone: us-south-3
>     ibm-cloud.kubernetes.io/worker-id: 0737_69aa2790-f4e4-4f8f-9260-661c1c164f48
>     kubernetes.io/arch: amd64
>     kubernetes.io/hostname: jdobson-cluster01-c5wc9-master-2
>     kubernetes.io/os: linux
>     node-role.kubernetes.io/master: ""
>     node.kubernetes.io/instance-type: bx2-4x16
>     node.openshift.io/os_id: rhcos
>     topology.kubernetes.io/region: us-south
>     topology.kubernetes.io/zone: us-south-3
>     vpc-block-csi-driver-labels: "true"
> ```
> 
> @ambiknai do you have any ideas?

@dobsonj  I will check and come back on this

**Comment by ambiknai** [comment]
@dobsonj  registrar version is `Version: v1.0.0-rc1-487-g629e85bf-dirty`.  can we use ` v2.2.0` and try

**Comment by jsafrane** [comment]
I am afraid registrar version won't help here. The driver must return non-empty `driverNodeID`.
https://github.com/container-storage-interface/spec/blob/ad238e5cad5a27188fcdae1ff3ace3f612638ca5/csi.proto#L1545-L1557

**Comment by dobsonj** [comment]
@ambiknai does this have a dependency on [vpc-node-label-updater v4.1.4](https://github.com/IBM/vpc-node-label-updater/releases/tag/v4.1.4)? We're still on v4.1.3 currently.

**Comment by ambiknai** [comment]
@dobsonj  I got confirmation from @prankulmahajan that v4.3 have a dependency on node-label-updater v4.1.4.

new label vpc-instance-id is added. Please could you use `v4.1.4.` once and try.

**Comment by dobsonj** [comment]
> Please could you use `v4.1.4.` once and try.

Sure, I ran into a couple of issues today though:
1) https://github.com/openshift/ibm-vpc-node-label-updater/pull/11 fails the CI checks due to https://github.com/IBM/vpc-node-label-updater/issues/10
2) openshift-install failed to create the cluster (timed out waiting for `ibm_is_image` image to be created). Not related to either rebase PR, just haven't been able to get a cluster start successfully with these changes yet.

**Comment by dobsonj** [comment]
Still getting failures when provisioning a cluster with these changes, but this time the bootstrap node fails to come up:
```
ERROR
ERROR Error: timeout while waiting for state to become 'running, available, failed, ' (last state: 'provisioning', timeout: 30m0s)
ERROR
ERROR   with ibm_is_instance.bootstrap_node,
ERROR   on main.tf line 11, in resource "ibm_is_instance" "bootstrap_node":
ERROR   11: resource "ibm_is_instance" "bootstrap_node" {
ERROR
ERROR failed to fetch Cluster: failed to generate asset "Cluster": failure applying terraform for "bootstrap" stage: failed to create cluster: failed to apply Terraform: exit status 1
ERROR
ERROR Error: timeout while waiting for state to become 'running, available, failed, ' (last state: 'provisioning', timeout: 30m0s)
ERROR
ERROR   with ibm_is_instance.bootstrap_node,
ERROR   on main.tf line 11, in resource "ibm_is_instance" "bootstrap_node":
ERROR   11: resource "ibm_is_instance" "bootstrap_node" {
ERROR
```
This is a little further in the process than the `ibm_is_image` error I hit before. The bootstrap instance was stuck in the "Starting" state and the boot volume was marked "failed". Looks like an issue with the backend service that creates the instances. This is in us-south-1.

**Comment by dobsonj** [comment]
> @dobsonj I got confirmation from @prankulmahajan that v4.3 has dependency on node-label-updater v4.1.4.
> 
> new label vpc-instance-id is added. Please could you use `v4.1.4.` once and try.

@ambiknai I got a cluster started with these changes, except for the driver which was stuck in a crash loop. Can you take a look at my notes in https://bugzilla.redhat.com/show_bug.cgi?id=2090263#c2 ?
Have you all had any successful deployments with the latest driver and node label updater releases?

**Comment by dobsonj** [comment]
Marking this as work-in-progress until we can get these issues resolved.
/retitle WIP: Rebase: ibm-vpc-block-csi-driver v4.3.0

**Comment by ambiknai** [comment]
> Marking this as work-in-progress until we can get these issues resolved.
> /retitle WIP: Rebase: ibm-vpc-block-csi-driver v4.3.0

Discussed with Jonathan and agreed to verify on a cluster once issue is recreated. We tested on IPI cluster [ deploy the driver / node labeler after the cluster was created] and did not face this issue. As Jonathan mentioned, deploy with new release fails.

**Pull request merged**
