### PR TITLE
[release-4.13] OCPBUGS-18143: [IBM VPC] failed provisioning volume in proxy cluster

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com//browse/OCPBUGS-18143

This is a manual backport of https://github.com/openshift/ibm-vpc-block-csi-driver/pull/46
Just updated ibmcloud-volume-interface to v1.2.0 and ran `go mod tidy && go mod vendor`
/cc @openshift/storage @duanwei33

Related operator PR: https://github.com/openshift/ibm-vpc-block-csi-driver-operator/pull/76

### CODE REVIEW

**Comment by duanwei33** [comment]
/hold 
(for per-merge verification)

**Comment by duanwei33** [comment]
Performing the pre-merge verification with open PR:
```
build 4.13.0-0.ci,openshift/ibm-vpc-block-csi-driver#47,openshift/ibm-vpc-block-csi-driver-operator#76
```

```
$ oc get clusterversion
NAME      VERSION                                                AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.13.0-0.test-2023-10-13-013428-ci-ln-fnf5gdk-latest   True        False         3h28m   Cluster version is 4.13.0-0.test-2023-10-13-013428-ci-ln-fnf5gdk-latest

```
The cluster proxy setting:
```
$ oc get proxies cluster -o yaml
status:
  httpProxy: http://proxy-user1:xxx@10.242.128.4:3128
  httpsProxy: http://proxy-user1:xxx@10.242.128.4:3128
  noProxy: .cluster.local,.svc,10.128.0.0/14,10.242.0.0/16,127.0.0.1,172.30.0.0/16,api-int.wduan-1012b-ibm.ibmcloud.qe.devcluster.openshift.com,localhost,test.no-proxy.com
```
The proxy in csi-driver container:
```
$ oc -n openshift-cluster-csi-drivers rsh -c csi-driver ibm-vpc-block-csi-controller-878856bb4-f8tb5
sh-4.4$ env | grep PROXY  
HTTP_PROXY=http://proxy-user1:xxx@10.242.128.4:3128
NO_PROXY=.cluster.local,.svc,10.128.0.0/14,10.242.0.0/16,127.0.0.1,172.30.0.0/16,api-int.wduan-1012b-ibm.ibmcloud.qe.devcluster.openshift.com,localhost,test.no-proxy.com
HTTPS_PROXY=http://proxy-user1:xxx@10.242.128.4:3128
```

The pv is provisioned successfully:

```
$ oc get pod,pvc
NAME               READY   STATUS    RESTARTS   AGE
pod/mypod-test-1   1/1     Running   0          73s

NAME                                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                 AGE
persistentvolumeclaim/mypvc-test-1   Bound    pvc-0c9b2e33-e0df-45bd-82d1-b407d8bf6767   10Gi       RWO            ibmc-vpc-block-10iops-tier   73s

```

**Comment by mpatlasov** [comment]
`ci/prow/e2e-ibmcloud-csi` is perma-failing. It failed in [PR#49](https://github.com/openshift/ibm-vpc-block-csi-driver/pull/49) exactly the same way as in this PR:

```
: Run multi-stage test e2e-ibmcloud-csi - e2e-ibmcloud-csi-ipi-deprovision-deprovision container test expand_less	1h10m1s
{  service-instances --type all" and "ibmcloud resource reclamations" to check for remaining instances, then delete the instances and try again.
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 1h0m0s timeout","severity":"error","time":"2023-10-16T20:26:05Z"}
Copying the Installer logs and metadata to the artifacts directory...
level=warning msg=Failed to delete resource group ci-op-mxlpjc62-9826d-hglb5: Resource groups with active or pending reclamation instances can't be deleted. Use the CLI commands "ibmcloud resource service-instances --type all" and "ibmcloud resource reclamations" to check for remaining instances, then delete the instances and try again.
level=warning msg=Failed to delete resource group ci-op-mxlpjc62-9826d-hglb5: Resource groups with active or pending reclamation instances can't be deleted. Use the CLI commands "ibmcloud resource service-instances --type all" and "ibmcloud resource reclamations" to check for remaining instances, then delete the instances and try again.
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:267","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 10m0s grace period","severity":"error","time":"2023-10-16T20:36:05Z"}
{"component":"entrypoint","error":"os: process already finished","file":"k8s.io/test-infra/prow/entrypoint/run.go:269","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Could not kill process after grace period","severity":"error","time":"2023-10-16T20:36:05Z"}
{"component":"entrypoint","error":"process timed out","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2023-10-16T20:36:05Z"}
error: failed to execute wrapped command: exit status 127
}
```

**Comment by mpatlasov** [comment]
@dobsonj , I cannot reproduce `go.mod` in the same form as in this PR. Here is what I did:
```
$ git checkout release-4.13

$ git log |head -1
commit 42b5c256657da2de184c3e5ec9c619131ed1cd57

$ go get github.com/IBM/ibmcloud-volume-interface@v1.2.0

$ grep "github.com/PuerkitoBio/" go.mod 
	github.com/PuerkitoBio/purell v1.1.1 // indirect
	github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578 // indirect
```

While in this PR the two lines go away: https://github.com/openshift/ibm-vpc-block-csi-driver/pull/47/commits/1e26147ba0c228c1aa2c2d81dd7433ce3098cb4c#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L32-L33

May be you used something else to update `go.mod`?

**Comment by duanwei33** [comment]
@dobsonj, @mpatlasov May I ask if there is any update?

**Comment by dobsonj** [comment]
> @dobsonj , I cannot reproduce `go.mod` in the same form as in this PR. Here is what I did:
> 
> ```
> $ git checkout release-4.13
> 
> $ git log |head -1
> commit 42b5c256657da2de184c3e5ec9c619131ed1cd57
> 
> $ go get github.com/IBM/ibmcloud-volume-interface@v1.2.0
> 
> $ grep "github.com/PuerkitoBio/" go.mod 
> 	github.com/PuerkitoBio/purell v1.1.1 // indirect
> 	github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578 // indirect
> ```
> 
> While in this PR the two lines go away: [1e26147#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L32-L33](https://github.com/openshift/ibm-vpc-block-csi-driver/commit/1e26147ba0c228c1aa2c2d81dd7433ce3098cb4c#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L32-L33)
> 
> May be you used something else to update `go.mod`?

@mpatlasov the short version is: that dependency is removed by `go mod tidy`.

Previously, `github.com/PuerkitoBio/purell` was required by `github.com/go-openapi/jsonreference`:

```
$ go mod why github.com/PuerkitoBio/purell
# github.com/PuerkitoBio/purell
github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/cmd
github.com/IBM/ibm-csi-common/pkg/metadata
k8s.io/client-go/kubernetes
k8s.io/client-go/discovery
k8s.io/client-go/openapi
k8s.io/kube-openapi/pkg/handler3
k8s.io/kube-openapi/pkg/validation/spec
github.com/go-openapi/jsonreference
github.com/PuerkitoBio/purell
```

But bumping this library pulls in `github.com/go-openapi/jsonreference@v0.20.0`

```
$ go get github.com/IBM/ibmcloud-volume-interface@v1.2.0
go: upgraded github.com/IBM/ibmcloud-volume-interface v1.1.2 => v1.2.0
go: upgraded github.com/IBM/secret-common-lib v1.1.2 => v1.1.4
go: upgraded github.com/IBM/secret-utils-lib v1.1.2 => v1.1.4
go: upgraded github.com/emicklei/go-restful/v3 v3.8.0 => v3.9.0
go: upgraded github.com/go-openapi/jsonreference v0.19.5 => v0.20.0
go: upgraded k8s.io/api v0.25.4 => v0.26.1
go: upgraded k8s.io/apimachinery v0.25.4 => v0.26.1
go: upgraded k8s.io/klog/v2 v2.70.1 => v2.80.1
go: upgraded k8s.io/kube-openapi v0.0.0-20220803162953-67bda5d908f1 => v0.0.0-20221012153701-172d655c2280
go: upgraded k8s.io/utils v0.0.0-20220728103510-ee6ede2d64ed => v0.0.0-20221107191617-1a15be271d1d
go: upgraded sigs.k8s.io/yaml v1.2.0 => v1.3.0
```

that version drops the PuerkitoBio dependency in https://github.com/go-openapi/jsonreference/commit/b112df9d9489b5deb974e8ded6ed6d75973167d5

So now those dependencies are no longer needed and `go mod tidy` removes them.

```
$ grep "github.com/PuerkitoBio/" go.mod
        github.com/PuerkitoBio/purell v1.1.1 // indirect
        github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578 // indirect
$ go mod why github.com/PuerkitoBio/purell            # github.com/PuerkitoBio/purell
(main module does not need package github.com/PuerkitoBio/purell)

$ go mod tidy && go mod vendor
$ grep "github.com/PuerkitoBio/" go.mod
$ 
```

**Comment by dobsonj** [comment]
> @dobsonj, @mpatlasov May I ask if there is any update?

I just rebased the PR, will ping for lgtm.

**Pull request merged**
