### PR TITLE
OCPBUGS-18105: [IBM VPC] failed provisioning volume in proxy cluster

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/OCPBUGS-18105

@duanwei33 found that the driver is still not using the proxy after setting the environment variables in https://github.com/openshift/ibm-vpc-block-csi-driver-operator/pull/74

I see a problem with the way the HTTP transport is created, looks like we should be setting the Proxy field with `http.ProxyFromEnvironment` if the CSI driver is to honor the proxy settings.

The code is in https://github.com/IBM/ibmcloud-volume-interface so if this fix is proven to work, then we'll need to get it upstream, and then bump the library.

### CODE REVIEW

**Comment by dobsonj** [comment]
Upstream PR: https://github.com/IBM/ibmcloud-volume-interface/pull/38

Once that merges, we'll need to bump the vendored version of ibmcloud-volume-interface in ibm-vpc-block-csi-driver upstream and then cherry-pick the bump in openshift.

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by dobsonj** [comment]
I see one test failure: `[sig-arch] events should not repeat pathologically for ns/openshift-cluster-csi-drivers`
But this is a flake, I see the same failures in https://github.com/openshift/ibm-vpc-block-csi-driver/pull/44 by openshift-bot. No connection to this proxy bug fix.
/unhold

**Pull request merged**
