### PR TITLE
STOR-867: Update ibm-vpc-block-csi-driver to the latest release

### PR DESCRIPTION
**Pull request by dobsonj**
[STOR-867](https://issues.redhat.com//browse/STOR-867): Update ibm-vpc-block-csi-driver to the latest release
https://issues.redhat.com/browse/STOR-867

- Fix format and mount failed (#90)
- Update golang version to 1.18 (#93)
- Updating ose-ibm-vpc-block-csi-driver images to be consistent with ART

https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/compare/v4.4.5...dobsonj:rebase-v4.4.5

/cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
```
level=error msg=failed to initialize the cluster: Cluster operators machine-api, monitoring are not available
```
/retest

**Comment by dobsonj** [comment]
DNS errors: `level=error msg=Error: An A, AAAA, or CNAME record with that host already exists.`
/retest

**Comment by dobsonj** [comment]
```
level=error msg=OAuthServerServiceEndpointsEndpointAccessibleControllerDegraded: oauth service endpoints are not ready
```
/retest

**Comment by dobsonj** [comment]
terraform timeout while uploading RHCOS image file
/retest

**Comment by jsafrane** [comment]
/label docs-approved
/label px-approved

We don't document / announce CSI driver version bumps to customers.

**Comment by chao007** [comment]
Regression test is passed

**Pull request merged**
